apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: souravdeveloper/woocart-client
          envFrom:
            - configMapRef:
                name: server-config
            - secretRef:
                name: server-secret
          env:
            - name: JWT_EXPIRE_IN
              value: 90d
---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client
  ports:
    - name: client
      port: 4000
      targetPort: 3000
      protocol: TCP
