apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: souravdeveloper/woocart-product
          envFrom:
            - configMapRef:
                name: server-config
            - secretRef:
                name: server-secret
          env:
            - name: JWT_EXPIRE_IN
              value: 90d
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product
  ports:
    - name: product
      port: 4000
      targetPort: 4000
      protocol: TCP
